sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - cmake
      - cmake-data
      - valgrind


before_install:
  - git submodule update --init --recursive

install:
  - pip install --user cpp-coveralls
  - pip install --user urllib3[secure]
  - export CXX="g++-5"
  - export CC="gcc-5"
  
script: 
  - g++-5 --version
  - cmake --version
  - mkdir Build
  - cd Build 
  - cmake ..
  - make
  - make test
  - ctest -T Memcheck
  - cd ..
  - mkdir Coverage
  - cd Coverage 
  - cmake -DCMAKE_BUILD_TYPE=Coverage --build . ..
  - make
  - make test 
  - cd ..

after_success:
  - coveralls -r . -b Coverage -e dep --gcov gcov-5 --verbose 
